### ISSUE TITLE
Racks.list returns different data than Racks.get 

### ISSUE THREAD

**Issue by Ladas** [tuskar/tuskar#55] opened 2013-07-24 08:52 UTC
curl -H "Accept: application/json" http://0.0.0.0:6385/v1/racks/1
{"slots": 3, "subnet": "192.168.1.0/24", "name": "compute_1", "links": [{"href": "http://0.0.0.0:6385/v1/racks/1", "rel": "self"}], "resource_class": {"id": 1, "links": [{"href": "http://0.0.0.0:6385/v1/resource_classes/1", "rel": "self"}]}, "capacities": [{"name": "total_cpu", "value": "64"}, {"name": "total_memory", "value": "16384"}], "state": "unprovisioned", "chassis": {}, "location": "room d2, row 1", "nodes": [{"id": "b21af596-a08d-4626-b9a4-c0fff946abf9", "links": [{"href": "http://ironic.local:6543/v1/b21af596-a08d-4626-b9a4-c0fff946abf9", "rel": "node"}]}, {"id": "3f9ebbf8-f324-4476-b1d9-629163ff0ba0", "links": [{"href": "http://ironic.local:6543/v1/3f9ebbf8-f324-4476-b1d9-629163ff0ba0", "rel": "node"}]}, {"id": "b99d536d-71aa-4dcc-acd6-ee75df9f9fa2", "links": [{"href": "http://ironic.local:6543/v1/b99d536d-71aa-4dcc-acd6-ee75df9f9fa2", "rel": "node"}]}], "id": 1}

 curl -H "Accept: application/json" http://0.0.0.0:6385/v1/racks
[{"slots": 3, "subnet": "192.168.1.0/24", "name": "compute_1", "links": [{"href": "http://0.0.0.0:6385/v1/racks/1", "rel": "self"}], "resource_class": {"id": 2, "links": [{"href": "http://0.0.0.0:6385/v1/resource_classes/2", "rel": "self"}]}, "capacities": [{"name": "total_cpu", "value": "64"}, {"name": "total_memory", "value": "16384"}], "state": "unprovisioned", "chassis": {}, "location": "room d2, row 1", "nodes": [{"id": "b21af596-a08d-4626-b9a4-c0fff946abf9", "links": [{"href": "http://ironic.local:6543/v1/b21af596-a08d-4626-b9a4-c0fff946abf9", "rel": "node"}]}, {"id": "3f9ebbf8-f324-4476-b1d9-629163ff0ba0", "links": [{"href": "http://ironic.local:6543/v1/3f9ebbf8-f324-4476-b1d9-629163ff0ba0", "rel": "node"}]}, {"id": "b99d536d-71aa-4dcc-acd6-ee75df9f9fa2", "links": [{"href": "http://ironic.local:6543/v1/b99d536d-71aa-4dcc-acd6-ee75df9f9fa2", "rel": "node"}]}], "id": 1}, {"slots": 3, "subnet": "192.168.2.0/24", "name": "compute_2", "links": [{"href": "http://0.0.0.0:6385/v1/racks/2", "rel": "self"}], "resource_class": {"id": 2, "links": [{"href": "http://0.0.0.0:6385/v1/resource_classes/2", "rel": "self"}]}, "capacities": [{"name": "total_cpu", "value": "64"}, {"name": "total_memory", "value": "16384"}], "state": "unprovisioned", "chassis": {}, "location": "room d2, row 2", "nodes": [{"id": "a579b880-df22-4ec8-a714-d1fa72c33952", "links": [{"href": "http://ironic.local:6543/v1/a579b880-df22-4ec8-a714-d1fa72c33952", "rel": "node"}]}, {"id": "b24a58a7-00b3-4378-9dd6-e292e9f6fb07", "links": [{"href": "http://ironic.local:6543/v1/b24a58a7-00b3-4378-9dd6-e292e9f6fb07", "rel": "node"}]}, {"id": "2fff8303-6e0e-461f-8866-cedce660dffd", "links": [{"href": "http://ironic.local:6543/v1/2fff8303-6e0e-461f-8866-cedce660dffd", "rel": "node"}]}], "id": 2}, {"slots": 3, "subnet": "192.168.3.0/24", "name": "not_compute", "links": [{"href": "http://0.0.0.0:6385/v1/racks/3", "rel": "self"}], "resource_class": {"id": 2, "links": [{"href": "http://0.0.0.0:6385/v1/resource_classes/2", "rel": "self"}]}, "capacities": [{"name": "total_cpu", "value": "64"}, {"name": "total_memory", "value": "16384"}], "state": "unprovisioned", "chassis": {}, "location": "room d2, row 3", "nodes": [{"id": "07abf8b9-8cfa-4acc-abbb-e1984e8d13c5", "links": [{"href": "http://ironic.local:6543/v1/07abf8b9-8cfa-4acc-abbb-e1984e8d13c5", "rel": "node"}]}], "id": 3}]

notice that "compute_1" has relation with resource_class 1 via get, via post it has relation with resource_class 2 (it's broken also in other racks)

Correct information are those obtained via get

**Comment by jistr** [comment] 2013-07-24 14:17
I cannot reproduce it on current master. I'm thinking it might have been caused by the misplaced return statements too. Could you please check on current master?

**Comment by jistr** [comment] 2013-07-25 10:36
Discussed with @Ladas, this is still an issue. A funny one. I can reproduce it now.

**Comment by mfojtik** [comment] 2013-07-26 08:44
This was fixed by @jistr. Closing.

**Closed as completed by mfojtik** 2013-07-26 08:44 UTC
Labels: bug, ui_blocker

**Comment by jistr** [comment] 2013-07-26 08:52
Yes we just checked that with @jcoufal, it works as expected.
